name: 'Publish Symbols'
description: 'Indexes and publishes PDB symbol files similar to Azure DevOps PublishSymbols@2.'

inputs:
  SymbolsPath:
    description: 'Target path to copy the generated symbols package.'
    required: false
    default: ' '
  SearchPattern:
    description: 'Pattern to search for PDB files.'
    required: true
    default: '**\\bin\\**\\*.pdb'
  SymbolsFolder:
    description: 'Root folder where symbol search starts.'
    required: false
    default: ' '
  SkipIndexing:
    description: 'Set to True to skip source indexing.'
    required: false
    default: 'False'
  TreatNotIndexingAsWarning:
    description: 'True to only warn if indexing fails.'
    required: false
    default: 'False'
  SymbolsVersion:
    description: 'Version metadata for the symbols.'
    required: false
    default: ' '
  SymbolsProduct:
    description: 'Product metadata for the symbols.'
    required: false
    default: ' '
  SymbolsArtifactName:
    description: 'Artifact name for the packaged symbols.'
    required: false
    default: 'Symbols_Release'

runs:
  using: "composite"
  steps:
    - name: Publish and Index Symbols
      shell: pwsh
      run: |
        Write-Host "Starting Symbol Publish Process..."
        # Minimal script to confirm YAML parsing works
        Write-Host "Action loaded successfully!"
